server:
  port: 8765
  ssl:
    key-store: classpath:keystore.dev.p12
    key-store-password: testing
    keyStoreType: PKCS12
    keyAlias: undertow

eureka:
  instance:
    metadataMap:
      instanceId:
        ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    healthcheck:
      enabled: true

zuul:
  ignoredServices: "*"
  routes:
    account-service: /api/account/**
  host:
    socket-timeout-millis: 30000
    connect-timeout-millis: 10000

ribbon:
  readTimeout: 10000
  connectTimeout: 10000

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

### for testing ###
security:
  user:
    name: 18656234569
    password: password
  sessions: ALWAYS
  #basic.enabled: false

management:
  security:
    enabled: false

athena:
  rememberMe.key: katrina

# Setting active profile
spring:
  profiles:
    active: dev

---
# Configuration for development
spring:
  profiles: dev
  output.ansi.enabled: always
  datasource:
    data: data-dev.sql
    url: jdbc:h2:mem:dev;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    show-sql: true

logging.level:
  com.athena: DEBUG
  org.springframework.security: DEBUG

---
# For deployment in docker containers
spring:
  profiles: docker
  redis:
    host: redis
    port: 6379
  rabbitmq:
      host: rabbitmq

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
