server:
  port: 8765
  ssl:
    key-store: classpath:keystore.dev.p12
    key-store-password: testing
    keyStoreType: PKCS12
    keyAlias: undertow

eureka:
  instance:
    metadataMap:
      instanceId:
        ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    healthcheck:
      enabled: true

zuul:
  ignoredServices: "*"
  routes:
    account-service: /api/account/**

### for testing ###
security:
  user:
    password: password
  sessions: ALWAYS
  #basic.enabled: false

management:
  security:
    enabled: false

---
# For deployment in docker containers
spring:
  profiles: docker
  redis:
    host: redis
    port: 6379
  rabbitmq:
      host: rabbitmq

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
