server:
  port: 8765

eureka:
  instance:
    metadataMap:
      instanceId:
        ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    healthcheck:
      enabled: true

zuul:
  ignoredServices: "*"
  routes:
    account-service: /api/account/**

### for testing ###
security.basic.enabled: false
management.security.enabled: false