rabbitmq:
  image: rabbitmq
#  net: "athena"
  ports:
    - "5672:5672"
    - "25672:25672"
    - "4369:4369"

redis:
  image: redis
#  net: "athena"
  ports:
    - "6379:6379"

discovery:
  image: tianjian/athena-service-discovery
#  net: "athena"
  ports:
    - "8761:8761"
  links:
    - redis
    - rabbitmq

edge:
  image: tianjian/athena-edge
  ports:
    - "443:8765"
#  net: "athena"
  links:
    - rabbitmq
    - redis
    - discovery

account:
  image: tianjian/athena-account
#  net: "athena"
  links:
    - rabbitmq
    - redis
    - discovery
