server:
  port: 8761

eureka:
  server:
    waitTimeInMsWhenSyncEmpty: 0
    registrySyncRetries: 0
    renewalPercentThreshold: 0.5
#    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
# For deployment in Docker containers
spring:
  profiles: docker
  rabbitmq:
    host: rabbitmq
