server:
  port: 0

eureka:
  instance:
    metadataMap:
      instanceId:
        ${spring.application.name}:${spring.application.instance_id:${random.value}}

security:
  sessions: NEVER

management.security.enabled: false

# Setting active profile
spring:
  output.ansi.enabled: always
  datasource:
    # schema: createAclSchema.sql
    # Due to the bug https://jira.spring.io/browse/SPR-12649,
    # we have to append the data initialization script to the schema
    data: data.sql
    url: jdbc:h2:mem:dev;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  profiles:
    active: dev

---
# Configuration for development
spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate.hbm2ddl.import_files:

logging.level:
  com.athena: DEBUG
  org.springframework.security: DEBUG

---
# For deployment in docker containers
spring:
  profiles: docker
  redis:
    host: redis
    port: 6379
  rabbitmq:
    host: rabbitmq

server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/