server:
  port: 0

eureka:
  instance:
    metadataMap:
      instanceId:
        ${spring.application.name}:${spring.application.instance_id:${random.value}}

security.basic.enabled: false
management.security.enabled: false
