server:
  port: 0

eureka:
  instance:
    metadataMap:
      instanceId:
        ${spring.application.name}:${spring.application.instance_id:${random.value}}

security:
  basic:
    enabled: false
  sessions: NEVER

management.security.enabled: false

---
# For deployment in docker containers
spring:
  profiles: docker
  redis:
    host: redis
    port: 6379
  rabbitmq:
      host: rabbitmq

server:
  port: 8080

eureka:
  instance:
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/