/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'brook.xi' at '11/16/15 8:37 PM' with Gradle 2.7
 *
 * @author brook.xi, @date 11/16/15 8:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
